# Generated by Django 2.1.1 on 2018-09-20 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoppinglist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listName', models.CharField(max_length=255)),
                ('budgetAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='budget_amount(KES)')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_shoppinglists',
            },
        ),
        migrations.CreateModel(
            name='ShoppinglistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='quantity')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='budget_amount(KES)')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('shoppinglist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to='shoppinglist.Shoppinglist')),
            ],
            options={
                'db_table': 'tbl_shoppinglist_items',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_users',
            },
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to='shoppinglist.User'),
        ),
    ]
