# Generated by Django 2.1.1 on 2018-09-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0002_auto_20180920_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='budgetBalance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='budget_balance(KES)'),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='bought',
            field=models.BooleanField(default=False),
        ),
    ]
