# Generated by Django 2.1.1 on 2018-09-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0003_auto_20180921_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='budgetBalance',
            new_name='budgetLimit',
        ),
    ]
